# Generated by Django 3.2.8 on 2021-10-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gocustomerstatus',
            name='documents',
            field=models.FileField(blank=True, default='', null=True, upload_to='%Y/customers/all_files/139897290571536/documents/', verbose_name='Customers files'),
        ),
    ]
