# Generated by Django 3.2.7 on 2021-09-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gocustomerstatus',
            name='value',
            field=models.IntegerField(verbose_name='Level'),
        ),
    ]
