# Generated by Django 3.2.7 on 2021-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gouser',
            name='profile',
            field=models.ImageField(default='profile1.png', upload_to='profiles/%Y/', verbose_name='Picture'),
        ),
    ]
